#Referensi:
#https://docs.gitlab.com/ee/ci/
#https://linux.die.net/man/1/rsync
#dan sumber-sumber lainnya.
before_script:
  - echo "Before script"
  - cd /home/gitlab-runner/builds/Dp6ckC1s/0/cmi-apps-project/cmos/

building:
  stage: build
  script:
    - composer install
    - sleep 10

deploying:
  stage: deploy
  script:
    - echo "Deploying to nginx root directory using rsync"
    - sudo rsync -a --progress --human-readable
      --exclude ".env"
      --exclude-from '.gitignore'
      --exclude .gitignore
      --exclude .git
      --exclude storage
      .
      /home/shipping/app
    - sudo chown -R nginx:nginx /home/shipping/app
    - sudo find /home/shipping/app -type f -exec chmod 664 {} \;
    - sudo find /home/shipping/app -type d -exec chmod 775 {} \;
    - sudo chmod -R ug+rwx storage bootstrap/cache
    - cd /home/shipping/app
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan view:clear
